logistic_regression:
  C: 10.0
  class_weight:
    '0': 0.2
    '1': 0.8
  max_iter: 500
  penalty: l2
  solver: sag
random_forest:
  bootstrap: false
  class_weight:
    '0': 0.2
    '1': 0.8
  max_depth: null
  min_samples_leaf: 2
  min_samples_split: 2
  n_estimators: 200
xgboost:
  n_estimators: 200
  min_samples_split: 2
  min_samples_leaf: 2
  max_depth: null
  class_weight:
    '0': 0.2
    '1': 0.8
  bootstrap: false
voting:
  weights:
  - 0.25 # logistic regression
  - 0.75 # random forest